name: All Database System Tests

on:
  pull_request:
    branches: [main]

# System matricies
x-macos-matrix: &macos-matrix
  '[{"os": "macos-13", "arch": "intel"}, {"os": "macos-14", "arch": "arm64"}, {"os": "macos-15", "arch": "arm64"}]'

x-linux-matrix: &linux-matrix
  '[{"os": "ubuntu-22.04", "arch": "x64"}, {"os": "ubuntu-24.04", "arch": "x64"}]'

jobs:
  # macOS database tests
  postgresql-macos:
    uses: ./.github/workflows/mac-system-tests/test-mac-system-postgres.yml
    with:
      os-matrix: *macos-matrix

  mysql-macos:
    uses: ./.github/workflows/mac-system-tests/test-mac-system-mysql.yml
    with:
      os-matrix: *macos-matrix

  sqlite-macos:
    uses: ./.github/workflows/mac-system-tests/test-mac-system-sqlite.yml
    with:
      os-matrix: *macos-matrix

  mongodb-macos:
    uses: ./.github/workflows/mac-system-tests/test-mac-system-mongo.yml
    with:
      os-matrix: *macos-matrix

  # requires custom matrix to specify database type
  postgresql-linux:
    uses: ./.github/workflows/ubuntu-system-tests/test-ubuntu-system-postgres.yml
    with:
      os-matrix: '[{"os": "ubuntu-22.04", "postgres_version": "14", "arch": "x64"}, {"os": "ubuntu-24.04", "postgres_version": "16", "arch": "x64"}]'

  # requires custom matrix to specify database type
  mysql-linux:
    uses: ./.github/workflows/ubuntu-system-tests/test-ubuntu-system-mysql.yml
    with:
      os-matrix: '[{"os": "ubuntu-22.04", "mysql_version": "8.0", "arch": "x64"}, {"os": "ubuntu-24.04", "mysql_version": "8.0", "arch": "x64"}]'
  
  sqlite-linux:
    uses: ./.github/workflows/ubuntu-system-tests/test-ubuntu-system-sqlite.yml
    with:
      os-matrix: *linux-matrix


